attach(olcum1)# IMPORT DATASET ADIMINDAN SONRA R PROGRAMINA VERI ATTACH EDILMEKTEDIR.
View(olcum1)#ATTACH EDILEN VERI VIEW KOMUTU ILE GÖSTERILIR.

shapiro.test(Sabah) #NORMAL DAGILIM TESTI


library(rcompanion)

plotNormalHistogram(Sabah)#NORMAL DAGILIM GRAFIGI

transformTukey(Sabah)#VERI NORMAL DAGILMIYOR ISE TRANSFORM KOMUTU ILE NORMAL DAGILIMA UYGUN HALE GETIRILIR.






